-- phpMyAdmin SQL Dump
-- version 5.1.0
-- https://www.phpmyadmin.net/
--
-- Host: 31.11.39.82:3306
-- Creato il: Gen 14, 2024 alle 09:31
-- Versione del server: 5.7.36-39-log
-- Versione PHP: 8.0.7

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `Sql1615711_3`
--

-- --------------------------------------------------------

--
-- Struttura della tabella `ticket`
--

CREATE TABLE `ticket` (
  `progr` int(11) NOT NULL,
  `codice` int(11) DEFAULT '0',
  `argomento` varchar(5000) DEFAULT NULL,
  `descrizione` varchar(5000) DEFAULT NULL,
  `dataora` datetime DEFAULT NULL,
  `login` varchar(50) DEFAULT NULL,
  `stato` varchar(20) DEFAULT 'APERTO',
  `lavorazione` varchar(20) DEFAULT 'PROGRESS',
  `datachiusura` datetime DEFAULT NULL,
  `allegato` varchar(50) DEFAULT NULL,
  `operatore` varchar(50) DEFAULT NULL,
  `procedura` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dump dei dati per la tabella `ticket`
--

INSERT INTO `ticket` (`progr`, `codice`, `argomento`, `descrizione`, `dataora`, `login`, `stato`, `lavorazione`, `datachiusura`, `allegato`, `operatore`, `procedura`) VALUES
(11, 245, 'Gestione soci', 'Buonasera, ho inserito il rinnovo dei soci e va tutto bene.ogni anno cambia il numero della tessera e quando modifico il numero tessere esce l\'errore. Alvaro Pacheco fernandina nuovo numero tesser 160474\r\nCordiali saluti \r\nAldo Guenzani', '2023-02-09 21:02:17', 'tommyguenzani@gmail.com', 'CHIUSO', 'RISOLTO', '2023-02-10 23:52:38', NULL, NULL, 'abacuscalla'),
(13, 247, 'REGISTRAZIONE MOVIMENTI CASSA BANCA', 'Buongiorno, ho riportato i saldi cassa e banca 2022 nell\'anno 2023.Ora devo registrare 3 movimenti da cassa a banca (150,00 - 150,00 200,00) ma giÃ  alla prima operazione mi dice che il credito Ã¨ insufficiente. Dove sbaglio?\r\nSaluti Aldo', '2023-02-12 17:02:21', 'tommyguenzani@gmail.com', 'CHIUSO', 'RISOLTO', '2023-02-13 14:05:13', NULL, NULL, 'abacuscalla'),
(15, 249, 'Modello D', 'Buongiorno, ho stampato il modello D dell\'anno 2022 e ho visto in alto la scritta CF e Cod. Runts, questi dati devo inserirli? in caso affermativo come faccio?\r\ngrazie . Buona giornata.\r\nAldo', '2023-02-16 11:02:26', 'tommyguenzani@gmail.com', 'CHIUSO', 'RISOLTO', '2023-02-19 19:57:22', NULL, NULL, 'abacuscalla'),
(16, 250, 'errore: dopo l\'immissione della quota pagata, in presenza di semaforo verde (ma il pallino colorato non appare ancora) si ottiene una pagina di errore, come sotto riportata,tornando indietro e ridando la quota pagata viene registrata e appare il pallino/semaforo verde', 'ERRORE gia\' presente&ERRORE movimento contabileinsert into movimenticontabili ( esercizio, mastro, sottomastro, conto, e_u, causale, importo, data, data_inserimento, tipodocumento, numdocumento, note, perciva, iva, login, ricevutapagamento, bancacassa, progetto, intesta ) values ( \'2023\', \'EA01\', \'0\', \'0\', \'E\', \'143\', \'7,50\', \'2023-02-23\', \'2023-02-23\', \'CONTANTI\', \'\', \'Pagamento quota sociale di BRUNO EMMA anno 2023\', \'\', \'0\', \'garbagnatemonasteroebrongio.lecco@ana.it\', \' \' , \'CASSA PRINCIPALE\', \'\' , \'\' )', '2023-02-23 13:02:46', 'garbagnatemonasteroebrongio.lecco@ana.it', 'CHIUSO', 'RISOLTO', '2023-03-01 17:00:10', NULL, NULL, 'abacuscalla'),
(17, 251, 'Ticket 2023', 'Buongiorno ho aggiornato il saldo ore 2022 di tutti i soci, ora sono in pari con gli assegni.\r\nHo fatto delle prove con gli assegni 2023 , Ã¨ possibile cancellare i movimenti 2023? Grazie', '2023-03-02 16:03:59', 'tommyguenzani@gmail.com', 'CHIUSO', 'RISOLTO', '2023-03-03 18:37:43', NULL, NULL, 'abacuscalla'),
(18, 252, 'inserimento bonus a ogni tesseramento o rinnovo', 'Buongiorno Domenico, la bdT di Legnano a ogni tesseramento o rinnovo regala 5 ore al socio, se il socio durante l\'anno non \"spende\" nessun assegno il bonus viene recuperato tutto  oppure se non \"spende\"  tutte le 5 ore viene recuperato la rimanenza del bonus.Per quanto riguardo il recupero ho creato una voce apposita mentre per inserire il bonus posso usare la funzione \" inserimento debito ore al socio per inizio esercizio\"? mi confonde la parola debito mentre io vorrei inserire un credito. In attesa di un tuo riscontro , ti ringrazio . Ciao Aldo', '2023-03-03 14:03:22', 'tommyguenzani@gmail.com', 'CHIUSO', 'RISOLTO', '2023-03-03 18:37:02', NULL, NULL, 'abacuscalla'),
(19, 253, 'Inserimento Codice errato', 'Buonasera ho inserito un codice sbagliato nelle Prestazioni: G - 05- tesseramento Ã¨ possibile toglierlo? Grazie\r\n( il codice giusto inserito Ã¨ G05 - Tesseramento )', '2023-03-13 19:03:48', 'tommyguenzani@gmail.com', 'CHIUSO', 'RISOLTO', NULL, NULL, 'DOMENICO', 'abacuscalla'),
(72, 307, 'Aggiustamenti vari', 'alcuni appunti\r\n\r\n1)  in \"Elenco soci estrazione dati in Excel\" nell\'elenco completo non appare chi non risulta abbia pagato la quota; non dovrebbe essere cosÃ¬ perchÃ¨ per questo c\'Ã¨ giÃ  \"l\'estrazione rinnovi\"\r\n\r\n2) i movimenti tra cassa e Banca non funzionano ancora o sono io che sbaglio?\r\n\r\nCordiali saluti\r\n\r\nRiva Gerolamo \r\n(segretario Alpini di Garbagnate Monastero)\r\n338 3165285', '2023-04-14 12:04:28', 'garbagnatemonasteroebrongio.lecco@ana.it', 'CHIUSO', 'RISOLTO', '2023-05-06 13:05:27', '', 'DOMENICO', 'abacuscalla'),
(73, 308, 'Riscontrato anomalia tecnica cassabanca.php', ' INSERT INTO \nmovimenticontabilicb (\nesercizio, \nmastro, \nsottomastro, \nconto,\ne_u,\ncausale,\nimporto,\ndata,\ndata_inserimento,\ntipodocumento,\nnumdocumento,\nnote,\nperciva,\niva,\nlogin,\nbancacassa,\nbanca\n) VALUES (\n\'2023\', \n\'0\', \n\'0\', \n\'0\',\n\'U\',\n\'CB\',\n\'1.\'09\',\n\'2023-04-17\',\n\'2023-04-17 11:04:52\',\n\'DISTINTA\',\n\'1\',\n\'1\',\n\'\',\n\'0\',\n\'mimmo\',\n\'cassa mia\',\n\'BANCA DELLA PIAZZA\'\n)', '2023-04-17 11:04:52', 'mimmo', 'CHIUSO', 'RISOLTO', '2023-04-17 11:04:21', '', 'DOMENICO', 'abacuscalla'),
(75, 310, 'Lista Assegni ', 'Nella lista assegni l\'anagrafica Ã¨ multipla', '2023-04-19 15:04:18', 'tommyguenzani@gmail.com', 'CHIUSO', 'RISOLTO', '2023-05-09 18:05:59', '', 'DOMENICO', 'abacuscalla'),
(76, 311, 'estratto conto', 'nell\'estratto conto non viene riportato correttamente il codice del Socio', '2023-04-19 15:04:25', 'tommyguenzani@gmail.com', 'CHIUSO', 'RISOLTO', '2023-05-09 18:05:19', '', 'DOMENICO', 'abacuscalla'),
(77, 312, 'Riscontrato anomalia tecnica cassabanca.php', ' INSERT INTO \nmovimenticontabilicb (\nesercizio, \nmastro, \nsottomastro, \nconto,\ne_u,\ncausale,\nimporto,\ndata,\ndata_inserimento,\ntipodocumento,\nnumdocumento,\nnote,\nperciva,\niva,\nlogin,\nbancacassa,\nbanca\n) VALUES (\n\'2023\', \n\'0\', \n\'0\', \n\'0\',\n\'U\',\n\'BB\',\n\'900.00\',\n\'2023-03-14\',\n\'2023-04-21 13:04:49\',\n\'VERSAMENTO TRAMITE ATM\',\n\'01\',\n\'\',\n\'\',\n\'0\',\n\'garbagnatemonasteroebrongio.lecco@ana.it\',\n\'Intesa San Paolo\',\n\'Intesa San Paolo\'\n)', '2023-04-21 13:04:49', 'garbagnatemonasteroebrongio.lecco@ana.it', 'CHIUSO', 'RISOLTO', '2023-05-06 13:05:23', '', 'DOMENICO', 'abacuscalla'),
(80, 315, 'estratto conto', 'buonasera, quando apro l\'estratto conto di ogni socio appare la scritta 503 servizio non disponibile', '2023-04-27 17:04:56', 'tommyguenzani@gmail.com', 'CHIUSO', 'RISOLTO', '2023-05-10 14:05:31', '', 'DOMENICO', 'abacuscalla'),
(81, 316, 'risultati discordanti', 'Al momento ho tralasciato di proseguire negli inserimenti perchÃ¨ non mi riesce di capire  come mai \r\n- nei movimenti contabili ho 4283,9 in entrata e 1343 in uscita (diff. 2904,4) \r\n- in estratto conto  ho 3893 in entrata e 1125 in uscita (diff. 2797,8)\r\n- e sul cruscotto ho un saldo in banca per 2768,22 + in cassa 172,27 (tot.2940,49).\r\nNei diversi campi di conteggio alcune voci sono fuori, perchÃ¨?\r\n\r\nQuando ha 5 minuti ci possiamo sentire nei prossimi giorni, fra lunedÃ¬ e martedÃ¬ (o settimana successiva)  per capire queste differenze ed i relativi dettagli? grazie\r\nRiva Gerolamo  cell. 3383165285', '2023-05-06 13:05:17', 'garbagnatemonasteroebrongio.lecco@ana.it', 'CHIUSO', 'RISOLTO', '2023-08-04 09:08:28', '', 'AMMINISTRATORE', 'abacuscalla'),
(83, 318, 'Riscontrato anomalia tecnica movimento.php', ' INSERT INTO \nmovimenticontabili (\nesercizio, \nmastro, \nsottomastro, \nconto,\ne_u,\ncausale,\nimporto,   \ndata,\ndata_inserimento,\ntipodocumento,\nnumdocumento,\nnote,\nperciva,\niva,\nlogin,\nbancacassa,\nprogetto,\nintesta,\ntipodocumentou,\n5xmilleparz,\nimportopar\n) VALUES (\n\'2023\', \n\'EA05\', \n\'0\', \n\'0\',\n\'E\',\n\'136\',\n\'10000\',\n\'2023-05-10\',\n\'2023-05-10 11:05:48\',\n\'PAGAMENTO VIRTUALE\',\n\'321\',\n\'anno 2021\',\n\'\',\n\'0\',\n\'p00006562@gmail.com\',\n\'Banca dell\'associazione\',\n\'NO\',\n\'Ministero del Lavoro\',\n\'LETTERA\',\n\'\',\n\'0\'\n)', '2023-05-10 11:05:48', 'p00006562@gmail.com', 'CHIUSO', 'RISOLTO', '2023-08-04 09:08:52', '', NULL, 'abacuscalla'),
(84, 319, 'RESIDENZA OSPITI', 'ABBIAMO NECESSITA\' DI REDIGERE DELLE STATISTICHE SELEZIONANDO E RIPARTENDO GLI OSPITI CHE ACCEDONO AL REFETTORIO, PER CITTA\' DI RESIDENZA.', '2023-05-29 17:05:21', 'esteposs', 'CHIUSO', 'RISOLTO', '2023-05-30 07:05:01', '', 'MARCO', 'ndspane'),
(85, 320, 'abilitazione nuovo utente: bonizzi mara', 'chiediamo abilitazione per nuovo accesso come sopra indicato', '2023-06-05 16:06:19', 'esteposs', 'APERTO', 'PROGRESS', NULL, '', 'AMMINISTRATORE', 'ndspane'),
(86, 321, 'Tabella AttivitÃ ', 'Buongiorno a tutti dovrei modificare alcune attivitÃ :\r\nCorreggere Musicaterapia da J19 a J18\r\nCorreggere N05 = Hardware- Software\r\naggiungere J19 = Massaggi\r\naggiungere P08 = Podologia\r\ntogliere   G07 = Volantini\r\ntogliere   N29 = consulenza finanziaria\r\nGrazie .\r\nCordiali saluti. Aldo', '2023-06-14 14:06:01', 'tommyguenzani@gmail.com', 'CHIUSO', 'RISOLTO', '2023-06-28 12:06:55', '', 'DOMENICO', 'abacuscalla'),
(87, 322, 'GESTIONE ARMADIO FARMACI', 'Buongiorno.\r\nAbbiamo riscontrato un errore nella gestione dello scarico dei farmaci.\r\nLa scorsa settimana, nello scaricare un pezzo di una referenza in giacenza, anzichÃ© ridurre la giacenza a 2 (3-1) l\'ha aumentata a 4 (3+1): alleghiamo screenshot.\r\nAltra cosa sempre relativa alla sezione di scarico farmaci: cosÃ¬ com\'Ã¨ pensato lo scarico Ã¨ parecchio difficoltoso, perchÃ¨ bisogna  scorrere tutte le referenze registrate per trovare la giusta combinazione di informazioni che permettano di individuare in farmaco da scaricare (vedasi sempre screenshot): Ã¨ possibile attivare una ricerca per nome del farmaco, magari in combinazione con il lotto, che renda piÃ¹ agevole lo scarico?\r\nRestiamo in attesa.\r\nSaluti.\r\nSimona Giordano', '2023-06-23 15:06:58', 'simogior', 'CHIUSO', 'RISOLTO', '2023-07-21 16:07:58', '-156.pdf', 'DOMENICO', 'ndspane'),
(88, 323, 'Inventario armadio farmaci', 'Questa funzione ha due problemi che sono bloccanti nella ricerca di un farmaco da somministrare/da scaricare:\r\n- non consente la ricerca per categoria ma solo per nome farmaco\r\n- nella stampa inventario non visualizza la categoria, ancorchÃ¨ correttamente registrata (alleghiamo screenshot).\r\nRestiamo in attesa.\r\nSaluti.\r\nSimona Giordano', '2023-06-23 16:06:49', 'simogior', 'CHIUSO', 'RISOLTO', '2023-07-21 16:07:25', '-157.2', 'DOMENICO', 'ndspane'),
(89, 324, 'Ripristino password per utente giusgent', 'Buongiorno.\r\nChiediamo che la password dell\'utente giusgent venga ripristinata in esachsel, in quanto il dottore non si ricorda piÃ¹ quella attuale.\r\nSaluti.\r\nSimona Giordano', '2023-06-23 17:06:08', 'simogior', 'CHIUSO', 'RISOLTO', '2023-06-24 08:06:06', '', 'MARCO', 'ndspane'),
(90, 325, 'ABILITAZIONE INVIO MAIL DA FUNZIONE SOCI', 'SE POSSIBILE ATTIVARE LA STESSA FUNZIONE GIA\' PERALTRO ATTIVA SUI VOLONTARI. QUESTO CI PERMETTEREBBE DI INVIARE SOLLECITI / REMINDER IN MODO PIU\' CAPILLARE.\r\nGRAZIE', '2023-06-27 16:06:40', 'esteposs', 'APERTO', 'PROGRESS', NULL, '', 'DOMENICO', 'ndspane'),
(91, 326, 'registrazione assegni', 'Buongiorno, quando registro un assegno della Banca del Tempo ,5a e 6a riga estratto conto, non appare il nome della banca del tempo ma si \"trascina\"il nome dell\'assegno precedente..in questo caso Solla.\r\nLa cosa si ripete con tutti i Soci.\r\nGrazie. Cordiali saluti. Aldo', '2023-06-29 16:06:03', 'tommyguenzani@gmail.com', 'CHIUSO', 'RISOLTO', '2023-08-04 11:08:49', '', 'DOMENICO', 'abacuscalla'),
(92, 327, 'ticket aperto ', 'invio foto estratto conto', '2023-06-29 16:06:48', 'tommyguenzani@gmail.com', 'CHIUSO', 'RISOLTO', '2023-08-02 20:08:14', '', 'DOMENICO', 'abacuscalla'),
(98, 333, 'richiesta', 'un disastro non funziona niente', '2023-07-26 10:07:32', 'progrint', 'CHIUSO', 'RISOLTO', '2023-08-21 10:08:30', '', NULL, 'progint'),
(99, 334, 'prova', 'prova', '2023-07-27 10:07:51', 'progrint', 'CHIUSO', 'RISOLTO', '2023-08-04 10:08:43', '', NULL, 'progint'),
(100, 335, 'provaxx', 'provaxx', '2023-07-27 10:07:31', 'progrint', 'CHIUSO', 'RISOLTO', '2023-10-12 14:10:50', '', NULL, 'progint'),
(101, 336, 'provayy', 'provayy', '2023-07-27 10:07:46', 'progrint', 'CHIUSO', 'RISOLTO', '2023-08-04 10:08:12', '', NULL, 'progint'),
(102, 337, 'MODIFICHE SU SEZIONE SOCI E VOLONTARI', 'NECESSITIAMO SEGUENTI MODIFICHE:\r\n1 RAPPORTARE LO STATO DEI SOCI ANCHE A VOLONTARI. NEL DETTAGLIO SUI VOLONTARI ANDREBBERO INSERITE LE SEGUENTI OPZIONI : NON ATTIVO E ASSEGNATO.\r\n2 I SEMAFORI DEVONO CORRISPONDERE (ATTUALMENTE SULLA SEZIONE VOLONTARI NON E\' POSSIBILE ESTRARRE IL ROSSO).\r\n3 ULTIMO RINNOVO : SE POSSIBILE LEGARE LO STATUS DELL\'ULTIMO ANNO DI RINNOVO DA SEZIONE SOCI A VOLONTARI.\r\nGRAZIE', '2023-07-31 18:07:37', 'esteposs', 'APERTO', 'PROGRESS', NULL, '', 'DOMENICO', 'ndspane'),
(103, 338, 'conteggio ore', 'Buongiorno, grazie per l\'assistenza che fornite ogni volta.\r\nVi scrivo per chiedere una cosa: Ã¨ possibile avere dal programma il totale ore scambiate? il conteggio si puÃ² fare anche per ogni attivitÃ ?\r\nsaluti . Aldo ', '2023-08-04 11:08:24', 'tommyguenzani@gmail.com', 'APERTO', 'PROGRESS', NULL, '', 'DOMENICO', 'abacuscalla'),
(104, 339, 'Scarico farmaci', 'Buongiorno.\r\nAbbiamo osservato che nella funzione \"Scarico farmaci in armadio\" non vengono visualizzati tutti i lotti dei diversi farmaci caricati a fronte della singola categoria.\r\n\r\nEsempio\r\nCategoria 20 CARDIOLOGICI ANTIPERTENSIVI BETABLOCCANTI\r\nFarmaco ATENOLOLO\r\nLotti caricati 7 per un totale di 9 pezzi in giacenza (fisicamente presenti nell\'armadio dei farmaci))\r\nNella tendina della funzione di scarico vengono visualizzati solo 4 lotti per un totale di 6 pezzi, rendendo di fatto impossibile lo scarico di tre pezzi dei tre lotti non visualizzati.\r\n\r\nAltra segnalazione: sarebbe bene che l\'inventario dei farmaci in armadio venisse stampato con orientamento orizzontale, in quanto la stampa verticale rende illeggibile una parte delle voci. \r\n\r\nGrazie!\r\n\r\nSimona\r\n\r\n\r\n', '2023-08-04 15:08:51', 'simogior', 'APERTO', 'PROGRESS', NULL, '-160.A_', 'DOMENICO', 'ndspane'),
(105, 340, 'ATTRIBUZIONE STATO OSPITI', 'AVREMMO NECESSITA\' DI AVERE CONFERMA SE E\' POSSIBILE PREVEDERE (NELLO STATO) ANCHE \"RESPINTO\" E CON LA CONFERMA CHE SIA NELLA RICERCA PER COGNOME E/O QR CODE EVIDENZI TALE POSIZIONE E NON CONSENTA L\'ACCESSO.', '2023-08-14 17:08:12', 'luvir', 'CHIUSO', 'RISOLTO', '2023-08-16 08:08:56', '', NULL, 'ndspane'),
(106, 341, 'Variazione nella richiesta di  mediazione', 'Vorremmo, nel caso in cui una mediazione giÃ  richiesta, venga modificata dall\'ente in una delle sue parti, ricevere un messaggio o un email.\r\n\r\nTale Messaggio/mail automatico  andrebbe inviato a:1) l\'operatore dell\'ente che ha effettuato la variazione 2) ai suoi responsabili se previsti 3) alla Cooperativa 4) al mediatore se la richiesta Ã¨ giÃ  abbinata.\r\nSe Ã¨ di difficile realizzazione vi chiediamo di non rendere possibile le modifiche da parte dell\'operatore dell\'ente.\r\n \r\nA disposizione per maggiori dettagli e per favore informatemi prima delle modifiche al sistema. Grazie mille\r\nDavid Jamous\r\n', '2023-10-12 14:10:32', 'progrint', 'CHIUSO', 'RISOLTO', '2023-11-06 22:11:02', '', 'DOMENICO', 'progint'),
(107, 342, 'mail Richiesta di disponibilitÃ  per mediazione linguistica', 'Nella mail non viene indicato il nome inserito #mediatore#\r\n\r\n\"Gentile ,\r\n\r\nchiediamo la sua disponibilitÃ  per effettuare la mediazione linguistica di cui al seguente link:\r\nhttps://www.progint.it/enti/menugenerale02.php?login=svetlana&chiave=Ric-2017\r\nLa invitiamo gentilmente a confermare la sua disponibilitÃ  o a rinunciare rispondendo a questa mail.\r\nCordiali saluti.\r\n\r\n\r\nProgetto Integrazione\r\nVia Volturno 28-30, 20124 Milano\r\nMetro Isola - Garibaldi\r\ninfo@progettointegrazione.it\r\n(+39) 02 66 98 60 00\"', '2023-11-02 10:11:26', 'progrint', 'CHIUSO', 'RISOLTO', '2023-11-06 10:11:43', '', 'DOMENICO', 'progint'),
(108, 343, 'File Mediatori e Operatori', 'Avrei bisogno (solo per l\'amministrazione) della possibilitÃ  di scaricare in excel la lista di tutti gli operatori degli enti e dei mediatori presenti in piattaforma.\r\nGrazie mille\r\nDavid Jamous\r\n', '2023-11-06 10:11:17', 'progrint', 'APERTO', 'PROGRESS', NULL, '', 'DOMENICO', 'progint'),
(109, 344, 'ISLAM MOHAMMAD ASFIKAR', 'Il nostro mediatore in oggetto Ã¨ non attivo. Purtroppo esce nella lista dei possibili abbinamenti. \r\nRiesce a non evidenziare la lista dei mediatori non attivi?\r\nGrazie\r\nDavid\r\n', '2023-11-06 16:11:04', 'progrint', 'CHIUSO', 'RISOLTO', '2023-11-07 16:11:10', '', 'DOMENICO', 'progint'),
(110, 345, 'ric-2048', 'Buongiorno abbiamo ricevuto una richiesta oggi 7 novembre alle ore 16.11 per una mediazione da effettuarsi oggi 7 novembre alle 11.00.\r\n\r\n\r\nVi chiediamo di inserire dei blocchi di avviso se richiedono una richiesta di mediazione con data antecedente la data di richiesta.\r\n\r\nGrazie mille\r\nDavid\r\n', '2023-11-07 16:11:38', 'progrint', 'CHIUSO', 'RISOLTO', '2024-01-10 23:01:49', '', 'DOMENICO', 'progint'),
(111, 346, 'lista mediazioni da fatturare', 'Nel foglio Excel che si scarica di tutte le mediazioni da fatturare non si possono gestire i filtri. Pertanto si ha un foglio excel con tutte le mediazioni da fatturare senza distinzione di cliente. In tal caso abbiamo bisogno di una aggiunta di colonna nel foglio excel legata al servizio di riferimento (ordinante A, B, fuori luoghi ...)\r\nGrazie mille\r\nDavid\r\n', '2023-11-08 16:11:11', 'progrint', 'CHIUSO', 'RISOLTO', '2023-11-21 10:11:33', '', 'DOMENICO', 'progint'),
(112, 347, 'Operatori', 'Salve Dobbiamo avere la possibilitÃ  di cancellare della lista degli operatori quelli che non si occuperanno del servizio. c\'Ã¨ la possibilitÃ  di modificare l\'anagrafica ma non di cancellare o rendere inattiva.\r\nGrazie', '2023-11-09 09:11:55', 'progrint', 'CHIUSO', 'RISOLTO', '2023-11-09 10:11:07', '', NULL, 'progint'),
(113, 348, 'LISTA/MODIFICA RICHIESTA  ', 'Nella sezione dedicata alla cooperativa LAVORO --> LISTA/MODIFICA RICHIESTA  viene compilato il campo LINGUA ALT anche se non viene indicata nel modulo di richiesta dellâ€™operatore. Sembra che prenda questo dato dalla tabella dei mediatori ma non Ã¨ corretto', '2023-11-09 12:11:52', 'progrint', 'CHIUSO', 'RISOLTO', '2023-11-21 10:11:11', '', 'DOMENICO', 'progint'),
(114, 349, 'ric 2074', 'Lo Storico della richiesta 2074 inizia il 8 novembre alle ore 14.11 mentre la richiesta sembra essere arrivata il 9 novembre\r\nVedete screen shot in allegato. sembra che manchi un alineamente tra le richieste\r\nGrazie mille\r\n\r\nDavid\r\n\r\n', '2023-11-09 17:11:46', 'progrint', 'APERTO', 'PROGRESS', NULL, '-162.pdf', NULL, 'progint'),
(115, 350, 'difficoltÃ  inserimento anno ', 'Buongiorno,\r\ncerco di inserire il mio primo socio (me stessa) ma non mi fa proseguire perchÃ¨ mi chiede l\'anno dell\'associazione ma la tendina Ã¨ vuota', '2023-11-15 10:11:07', 'servinosonia@yahoo.it', 'CHIUSO', 'RISOLTO', '2023-11-27 10:11:05', '', 'MARCO', 'abacuscalla'),
(116, 351, 'Problemi vari', '1) avendo necessitÃ  di inserire l\'anno 2022 per avere nel modello D  i dati dell\'anno precedente. Sono passato a questo e inserito le entrate e le uscite con qualche problema di corrispondenza col modello precedentemente utilizzato l\'anno scorso, per cui avrei bisogno di entrare nel dettaglio quando possiamo sentirci. \r\nInoltre sono emersi 2 altri problemini. 1)nell\'immissione dei costi figurativi sia l\'attivitÃ  dii interesse generale che le attivitÃ  diverse sono raggruppate sul mod. D in un unica voce;\r\n2)non mi Ã¨ possibile riaprire nuovamente l\'anno 2023 \"perchÃ¨ Ã¨ stato chiuso\"!!! \r\nAllora ho chiuso il 2022 e aquesto punto non si puÃ² riaprire nessuno dei 2 per sistemare i dettagli. \r\n\r\nAllego il mod. \"D 2022\" che avevo inviato a suo tempo al RUNTS per un confronto sui dati allora immessi e che dovrei fare combaciare sul nuovo modello D 2023. Ovviamente dho bisogno di riaprire entrambi i modelli per completarli.\r\n\r\nRingraziando per l\'attenzione porgo cordiali saluti\r\nRiva Gerolamo, (Associazione Alpini di Garbagnate Monastero e Brongio) cell. 338 3165285\r\nrivager@gmail.com\r\n', '2023-11-23 12:11:15', 'garbagnatemonasteroebrongio.lecco@ana.it', 'APERTO', 'PROGRESS', NULL, '-163.pdf', 'DOMENICO', 'abacuscalla'),
(117, 353, 'Riscontrato anomalia tecnica movimento.php', ' INSERT INTO \nmovimenticontabili (\nesercizio, \nmastro, \nsottomastro, \nconto,\ne_u,\ncausale,\nimporto,   \ndata,\ndata_inserimento,\ntipodocumento,\nnumdocumento,\nnote,\nperciva,\niva,\nlogin,\nbancacassa,\nprogetto,\nintesta,\ntipodocumentou,\n5xmilleparz,\nimportopar\n) VALUES (\n\'2023\', \n\'EA04\', \n\'0\', \n\'0\',\n\'E\',\n\'65\',\n\'100\',\n\'2023-12-13\',\n\'2023-12-19 16:12:22\',\n\'BONIFICO\',\n\'1\',\n\'EROGAZIONE LIBERALE DA ANONIMO\',\n\'\',\n\'0\',\n\'p00006562@gmail.com\',\n\'Banca dell\'associazione\',\n\'NO\',\n\'ANONIMO\',\n\'GENERICO\',\n\'\',\n\'0\'\n)', '2023-12-19 16:12:22', 'p00006562@gmail.com', 'CHIUSO', 'RISOLTO', '2024-01-11 11:01:11', '', NULL, 'abacuscalla'),
(118, 354, 'Riscontrato anomalia tecnica movimento.php', ' INSERT INTO \nmovimenticontabili (\nesercizio, \nmastro, \nsottomastro, \nconto,\ne_u,\ncausale,\nimporto,   \ndata,\ndata_inserimento,\ntipodocumento,\nnumdocumento,\nnote,\nperciva,\niva,\nlogin,\nbancacassa,\nprogetto,\nintesta,\ntipodocumentou,\n5xmilleparz,\nimportopar\n) VALUES (\n\'2023\', \n\'EA04\', \n\'0\', \n\'0\',\n\'E\',\n\'65\',\n\'100\',\n\'2023-12-13\',\n\'2023-12-19 16:12:29\',\n\'BONIFICO\',\n\'1\',\n\'Donazione\',\n\'\',\n\'0\',\n\'p00006562@gmail.com\',\n\'Banca dell\'associazione\',\n\'NO\',\n\'Anonimo\',\n\'GENERICO\',\n\'\',\n\'0\'\n)', '2023-12-19 16:12:29', 'p00006562@gmail.com', 'CHIUSO', 'RISOLTO', '2024-01-06 16:01:26', '', 'DOMENICO', 'abacuscalla'),
(119, 355, 'Avanzo di cassa e banca su mod.D non corrisponde con dati Cruscotto', 'Per l\'anno 2023 sul Cruscotto risulta un avanzo di cassa per â‚¬ 172,50 e di Banca â‚¬ 2488,81 \r\nmentre sul rendiconto mod.D risulta una Cassa di 823,59 e un avanzo in Banca di 1657,97. Non dovrebbero coincidere?', '2024-01-04 09:01:24', 'garbagnatemonasteroebrongio.lecco@ana.it', 'CHIUSO', 'RISOLTO', '2024-01-06 16:01:32', '', 'DOMENICO', 'abacuscalla'),
(120, 356, 'Riscontrato anomalia tecnica movimento.php', ' INSERT INTO \nmovimenticontabili (\nesercizio, \nmastro, \nsottomastro, \nconto,\ne_u,\ncausale,\nimporto,   \ndata,\ndata_inserimento,\ntipodocumento,\nnumdocumento,\nnote,\nperciva,\niva,\nlogin,\nbancacassa,\nprogetto,\nintesta,\ntipodocumentou,\n5xmilleparz,\nimportopar\n) VALUES (\n\'2023\', \n\'EA04\', \n\'0\', \n\'0\',\n\'E\',\n\'65\',\n\'100\',\n\'2023-12-19\',\n\'2024-01-09 16:01:23\',\n\'BONIFICO\',\n\'1\',\n\'Donazione\',\n\'\',\n\'0\',\n\'marco\',\n\'BPM - FILIALE DI MAGENTA\',\n\'NO\',\n\'Auser Filo d\'Argento Trecate\',\n\'GENERICO\',\n\'\',\n\'0\'\n)', '2024-01-09 16:01:23', 'marco', 'CHIUSO', 'RISOLTO', '2024-01-10 23:01:03', '', 'DOMENICO', 'abacuscalla'),
(121, 357, 'SERVIZIO 3016', 'HO INSERITO IL SERVIZIO IN MODO ERRATO. SI RIESCE A CANCELLARE IL SERVIZIO 3016?\r\nGRAZIE MILLE\r\n', '2024-01-12 16:01:04', 'progrint', 'APERTO', 'PROGRESS', NULL, '', 'DOMENICO', 'progint');

--
-- Indici per le tabelle scaricate
--

--
-- Indici per le tabelle `ticket`
--
ALTER TABLE `ticket`
  ADD PRIMARY KEY (`progr`);

--
-- AUTO_INCREMENT per le tabelle scaricate
--

--
-- AUTO_INCREMENT per la tabella `ticket`
--
ALTER TABLE `ticket`
  MODIFY `progr` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=122;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
